const Type = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SIGN_UP: "SIGN_UP",
  RESET_PASSWORD: "RESET_PASSWORD",
  NEW_PASSWORD: "NEW_PASSWORD",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  EDIT_PRODUCT: "EDIT_PRODUCT"
};

export default Type;
